name: nvm-action
on: push
jobs:
    nvm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up node using nvm
              uses: dcodeIO/setup-node-nvm@v4.0.0
            - run: node -v
