name: nvm
on: push
jobs:
    nvm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - shell: bash -l {0}
              run: |
                  nvm install
                  node -v
            - run: node -v
            - shell: bash -l {0}
              run: |
                  nvm install
                  node -v
